-- MySQL Script generated by MySQL Workbench
-- Fri Jan 28 21:01:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb_bentec
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb_bentec
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb_bentec` ;
USE `mydb_bentec` ;

-- -----------------------------------------------------
-- Table `mydb_bentec`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_bentec`.`tb_usuario` (
  `id_tb_usuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tb_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_bentec`.`tb_cadastro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_bentec`.`tb_cadastro` (
  `id_tb_cadastro` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(45) NULL,
  `sobrenome_cliente` VARCHAR(45) NULL,
  `idade_cliente` VARCHAR(45) NULL,
  `data_nascimento_cliente` DATE NULL,
  `sexo_cliente` VARCHAR(45) NULL,
  `cpf_cliente` VARCHAR(45) NULL,
  `codigo_cliente` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tb_cadastro`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
